excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cgetti.github.io
title: Awesome
email: caitlin.gettinger@gmail.com
author: Caitlin Gettinger
description: My awesome new site
paginate: 3
google_analytics: 